### ISSUE TITLE
support for setAll and mergeAll

### ISSUE THREAD

**Issue by edgesoft** [christianalfoni/cerebral-immutable-js#1]
Currently if I have multiple properties in a List that I want to update I must iterate over the map and do state.set or state.merge for every item in the array. Would be terrific if we could just update everything in one batch. Given this state

``` js
files: [
 {
    name : "test1",
    selected : false
  },
  {
    name : "test2",
    selected : true
  },
   {
    name : "test3",
    selected : false
  },
   {
    name : "test4",
    selected : false
  },
   {
    name : "test5",
    selected : false
  },
]

```

An operation like this...

``` js
state.merge(['files' , [0...5,7...10 ]], {selected:true})
```

or ...

``` js
state.merge(['files', {selected:false} ] , {selected:true});
```

**Comment by christianalfoni** [comment]
Moved to: https://github.com/cerebral/cerebral/issues/143
